name: xyz
main: unerds\xyz\xyz
version: 1.0.2
api: [2.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]

load: POSTWORLD
author: unerds
description: command to display player coordinates
website: github.com/unerds
commands:
 xyz:
  description: Returns Player Coordinates
  usage: "/xyz"
  permission: xyz.command.xyz